name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
- name: Install Android SDK tools
      uses: android-actions/setup-android@v3

    - name: Accept SDK licenses
      run: |
        yes | sdkmanager --licenses || true
        sdkmanager "build-tools;33.0.0" "platforms;android-33"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install --upgrade cython==0.29.36 buildozer

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
